config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :projects
  resources :users
  resources :messages

  patch '/users/:id' => 'users#update', as: 'update_user'
  root 'projects#index'

  get '/projects/show' => 'projects#show', as: 'show_projects'
  delete '/projects/destroy' => 'projects#destroy', as: 'delete_projects'
  delete '/users/destroy' => 'users#destroy', as: 'destroy_skill'
  delete '/messages/destroy' => 'messages#destroy', as: 'destroy_message'

end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :sender, class_name: "User", foreign_key: "sender_id"
  belongs_to :receiver, class_name: "User", foreign_key: "receiver_id"

  has_many :users
  has_many :projects
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    @messages = Message.where(receiver_id: current_user.id)
  end


  def show
  end

  def new
    @message = Message.new
    @sender = User.find(params[:sender_id])
    @project = Project.find(params[:project_id])
    current_user.projects << @project
    @user_project = UserProject.where(project_id: @project.id, user_id: current_user.id).first
    @user_project.update(status: 1)
    @content = "#{@sender.username} would like to join #{@project.name}. Do you accept?"
    @message.update(sender_id: @sender.id, receiver_id: @project.user.id, project_id: @project.id,
      content: @content)
    @message.save
    redirect_to :back
  end

  def destroy
    @user = User.find(params[:sender_id])
    @project = Project.find(params[:project_id])
    @user_project = UserProject.where(user_id: @user.id, project_id: @project.id).first
    @user_project.update(status: params[:status])
    @user_project.save
    Message.find(params[:id]).destroy
    redirect_to messages_path
  end

end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/index.html.haml
%h1
  Your Messages
%br
%ul{class: "list-group"}
-if @messages.blank?
  %li{class: "list-group-item"}
    None
-else
  -@messages.each do |message|
    %li{class: "list-group-item"}
      =message.content
    %li{class: "list-group-item"}
      =button_to "Yes", message_path(message.id, status: 2, sender_id: message.sender_id, project_id: message.project_id), method: :delete, class: 'btn btn-default'
      =button_to "No", message_path(message.id, status: 0, sender_id: message.sender_id, project_id: message.project_id), method: :delete, class: 'btn btn-default'
  %br