config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :projects
  resources :users
  resources :messages

  patch '/users/:id' => 'users#update', as: 'update_user'
  root 'projects#index'

  get '/projects/show' => 'projects#show', as: 'show_projects'
  delete '/projects/destroy' => 'projects#destroy', as: 'delete_projects'
  delete '/users/destroy' => 'users#destroy', as: 'destroy_skill'
  delete '/messages/destroy' => 'messages#destroy', as: 'destroy_message'

end

app/models/user.rb
class User < ActiveRecord::Base
	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable, :registerable,
	     :recoverable, :rememberable, :trackable, :validatable

	validates :email, presence: true, :length => {in: 5..255}, :email => true,
            uniqueness: true

   validates :username, presence: true, length: {in: 5..50}, uniqueness: true

  has_many :sent_messages, class_name: "Message", foreign_key: "sender_id"
  has_many :received_messages, class_name: "Message", foreign_key: "receiver_id"

  has_many :user_projects
  has_many :projects, through: :user_projects

  has_many :user_skills
  has_many :skills, through: :user_skills

  accepts_nested_attributes_for :skills, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :user_skills

  belongs_to :project
  belongs_to :skill

end # end class User

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @user = current_user
    @projects = @user.projects
    @skills = @user.skills
    @skill_categories = SkillCategory.all
    @hosted_projects = @projects.where(user_id: current_user.id)
    @all_status_joined_projects = @projects.where.not(user_id: current_user.id)
    @joined_projects = []
    @all_status_joined_projects.each do |joined_project|
      @user_project = UserProject.where(project_id: joined_project.id, user_id: current_user.id).first
      if @user_project.status == 2
        @joined_projects << joined_project
      end
    end
    if params[:project_id] && @projects.where(id: params[:project_id]).empty?
      current_user.projects << Project.find(params[:project_id])
    end
    @user.save
  end

  def show
    redirect_to '/users'
  end

  def create
    redirect_to '/users'
  end

  def destroy
    current_user.skills.find(params[:format]).destroy
    redirect_to :back
  end

  def edit
  end

  def update
    flash[:update] = params[:user][:user_skills_attributes]
    params[:user][:user_skills_attributes].each do |key, value|
      if current_user.skills << Skill.find(value[:skill_id])
      end
    end
    if current_user.save
      flash[:update] = "Skills added successfully"
    end
    redirect_to '/users/index'
  end

end

app/helpers/user_helper.rb
module UserHelper
end

app/views/users/_user_skill_fields.haml
.nested-fields.user-skill-fields
  .field
    =f.input :id, label: "Narrow skill search by category: ",
      collection: @skill_categories, label_method: :category,
      input_method: :id,
      input_html: { class: "skill_category_select_form" }
  .field
    = f.association :skill, label: "Choose a skill: ",
      collection: Skill.all
    = link_to_remove_association "remove skill", f
  %br

app/views/users/index.html.haml
%div{ class: "profile" }
  .page-header{ class: "header" }
    %h1
      Profile
      %small
        Get involved

  %div{ class: "projects" }
    %h2{ class: "title" }
      %strong
        Projects

    %div{ class: "hosted-projects row" }
      %h3{ class: "subtitle" }
        %u
          Your Hosted Projects

      %ul{class: "list-group"}
        -if @hosted_projects.blank?
          %li{class: "list-group-item no-item"}
            None
        -else
          - @hosted_projects.each do |p|
            %div{class: "project col-md-6"}
              %li{class: "list-group-item"}
                %strong
                  Name:
                = p.name
              %li{class: "list-group-item"}
                %strong
                  Public Description:
                = p.public_description
              %li{class: "list-group-item"}
                %strong
                  Private Description:
                = p.private_description
              %li{class: "list-group-item col-xs-6 edit"}
                = link_to "Edit Project", edit_project_path(p.id)
              %li{class: "list-group-item col-xs-6 delete"}
                = link_to "Delete Project", project_path(p.id),
                  method: :delete
    %div{class: "joined-projects row"}
      %h3{class: "subtitle"}
        %u
          Your Joined Projects

      %ul{class: "list-group"}
        -if @joined_projects.blank?
          %li{class: "list-group-item no-item"}
            None
        -else
          - @joined_projects.each do |p|
            %li{class: "list-group-item"}= p.name
            %li{class: "list-group-item"}= p.public_description
            %li{class: "list-group-item"}= p.private_description
            %li{class: "list-group-item"}
              = link_to "Leave Project", project_path(p.id, joined: true),
                method: :delete

  %div{class: "skills"}
    %h2{class: "title"}
      %strong
        Skills
    %ul{class: "list-group"}
      -if @skills.blank?
        %li{class: "list-group-item no-item"}
          None
        %br
      -else
        -@skills.each do |skill|
          %li{class: "list-group-item skill col-xs-12 col-sm-6 col-md-3"}
            =skill.skill
            =link_to "Delete Skill", destroy_skill_path(skill.id),
              method: :delete

      =simple_form_for @user,
        method: 'patch' do |f|

        #skills
          =f.simple_fields_for :skills do |user_skill|
            .nested-fields.user-skill-fields
              .field
                =f.input :id, label: "Narrow skill search by category: ",
                  collection: @skill_categories, label_method: :category,
                  input_method: :id,
                  input_html: { class: "skill_category_select_form" }
              .field
                = f.association :skills, label: "Choose a skill: ",
                  collection: Skill.all
                = link_to_remove_association "remove skill", f
              %br
          =link_to_add_association 'add skill', f, :user_skills
        %br
        =f.button :submit

  = link_to('Edit registration', edit_user_registration_path)