config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :projects
  resources :users
  resources :messages

  patch '/users/:id' => 'users#update', as: 'update_user'
  root 'projects#index'

  get '/projects/show' => 'projects#show', as: 'show_projects'
  delete '/projects/destroy' => 'projects#destroy', as: 'delete_projects'
  delete '/users/destroy' => 'users#destroy', as: 'destroy_skill'
  delete '/messages/destroy' => 'messages#destroy', as: 'destroy_message'

end

app/models/project.rb
class Project < ActiveRecord::Base

  has_many :user_projects
  has_many :users, through: :user_projects

  has_many :project_skills
  has_many :skills, through: :project_skills

  accepts_nested_attributes_for :skills, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :project_skills

  belongs_to :project_category
  belongs_to :user
  belongs_to :skill

  validates :name, presence: true
  validates :public_description, presence: true
  validates :private_description, presence: true
  validates :project_category, presence: true

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController


  def index

    # initially show all project categories
    @categories = ProjectCategory.all


  end

  def show

    # show all projects under the selected project category
    @projects = Project.where(project_category_id: params[:project_category_id])
    if current_user
      @user_projects = UserProject.where(user_id:current_user.id)
    end

  end

  def new
    if !user_signed_in?
      flash.alert = "Users must be signed up to log in"
      redirect_to new_user_session_path
    end
    @project = Project.new
    @categories = ProjectCategory.all
    @skill_categories = SkillCategory.all
  end

  def create
    @project = Project.new(project_params)
    @project.user_id = current_user.id
    if @project.save
      current_user.projects << @project
      @user_project = UserProject.where(project_id: @project.id, user_id: current_user.id).first
      @user_project.update(status: 2)
      flash[:update] = "Project created successfully"
    else
      flash[:error] = @project.errors.full_messages.to_sentence
    end
    redirect_to :back

  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find_by(params[:id])
    @name = params[:project][:name]
    @public_description = params[:project][:public_description]
    @private_description = params[:project][:private_description]
    @project.update(name: @name, public_description: @public_description,
                  private_description: @private_description)
    if @project.save
      flash[:update] = "Project successfully updated"
    end
    redirect_to root_path
  end

  def destroy
    @project = Project.find_by(params[:id])
    if params[:joined]
      current_user.projects.delete @project
      flash[:update] = "Left project successfully"
    else
      @project.destroy
      flash[:update] = "Project deleted successfully"
    end
    redirect_to :back
  end

  private

    def project_params
      params.require(:project).permit(:name, :public_description,
        :private_description, :project_category_id,
        project_skills_attributes: [:skill_id, :_destroy])
    end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_project_skill_fields.html.haml
.nested-fields.project-skill-fields
  .field
    =f.input :id, label: "Narrow skill search by category: ",
      collection: @skill_categories, label_method: :category,
      input_method: :id,
      input_html: { class: "skill_category_select_form" }
  .field
    = f.association :skill, label: "Choose a skill: ",
      collection: Skill.all
    = link_to_remove_association "remove skill", f
  %br

app/views/projects/edit.html.haml
= simple_form_for @project do |f|
  %br
  =f.input :name, label: "Name", autofocus: true
  %br
  =f.input :public_description, label: "Public Description"
  %br
  =f.input :private_description, label: "Private Description"
  %br

= link_to 'Back', :back

app/views/projects/index.html.haml
.page-header
  %h1
    Join a Project
    %small
      Get involved

- @categories.each do |category|
  = link_to category.project_category, show_projects_path(project_category_id: category.id), method: :get, class: 'btn btn-default inline'

app/views/projects/new.html.haml
%div{class: "new-project-section"}
  %h1{class: "title"} New Project
  = simple_form_for @project do |f|
    %br
    =f.input :project_category_id, label: "Select a project category: ",
      collection: @categories, label_method: :project_category, value_method: :id
    %br
    =f.input :name, label: "Project Name: ", autofocus: true
    %br
    =f.input :public_description, label: "Public Description: ",
      size: 1000
    %br
    =f.input :private_description, label: "Private Description: ",
      size: 1000
    %br
    #skills
      =f.simple_fields_for :skills do |project_skill|
        =render 'project_skill_fields', f: project_skill
      =link_to_add_association 'add skill', f, :project_skills
    %br
    = f.button :submit, "Create New Project!"

  =link_to 'Back', :back

app/views/projects/show.html.haml
%h1
  Here are the available projects in this category:
-if @projects.blank?
  %ul{class: "list-group"}
    %li{class: "list-group-item"}
      None
-else
  -@projects.each do |project|
    -if current_user then @user_project = @user_projects.where(project_id: project.id).first
      %ul{class: "list-group"}
        %li{class: "list-group-item"}
          %strong
            Project Name:
          =project.name
        %li{class: "list-group-item"}
          %strong
            Public Description:
          =project.public_description
        %li{class: "list-group-item"}
          %strong
            Skills Required:
        %ul{class: "list-group"}
          -project.skills.each do |skill|
            %li{class: "list-group-item"}
              =skill.skill
        %li{class: "list-group-item"}
          %strong
            -if @user_project.nil?
              =link_to "Request To Join Project",
                new_message_path(sender_id: current_user.id,
                project_id: project.id)
            -elsif @user_project.status == 0
              Your request to join this project was denied!
            -elsif @user_project.status == 1
              Your request to join this project is pending!
            -elsif @user_project.status == 2
              You're already part of this project!
            -else
              This shouldn't be here
      %br